Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: ${self:custom.environment.DOMAIN_NAME}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: ${self:custom.environment.DOMAIN_NAME}
          HostedZoneId: !ImportValue ${self:provider.stage}-HostedZoneId  # From DNS stack
Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Export:
      Name: !Sub "${self:provider.stage}-CertificateArn"