sit:
  KOOP_CONTAINER_PORT: 9000
  KOOP_DESIRED_COUNT: 0
  KOOP_DOMAIN: "${self:provider.stage}-koop.mapkraken.com"
  KOOP_ECR_URL: "${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:provider.stage}-koop:latest"
  TERRIAMAP_CONTAINER_PORT: 3001
  TERRIAMAP_DESIRED_COUNT: 0
  TERRIAMAP_DOMAIN: "${self:provider.stage}-terriamap.mapkraken.com"
  TERRIAMAP_ECR_URL: "${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:provider.stage}-terriamap:latest"
stg:
  KOOP_CONTAINER_PORT: 9000
  KOOP_DESIRED_COUNT: 1
  KOOP_DOMAIN: "${self:provider.stage}-koop.mapkraken.com"
  KOOP_ECR_URL: "${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:provider.stage}-koop:latest"
  TERRIAMAP_CONTAINER_PORT: 3001
  TERRIAMAP_DESIRED_COUNT: 1
  TERRIAMAP_DOMAIN: "${self:provider.stage}-terriamap.mapkraken.com"
  TERRIAMAP_ECR_URL: "${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:provider.stage}-terriamap:latest"
prd:
  KOOP_CONTAINER_PORT: 9000
  KOOP_DESIRED_COUNT: 1
  KOOP_DOMAIN: "${self:provider.stage}-koop.mapkraken.com"
  KOOP_ECR_URL: "${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:provider.stage}-koop:latest"
  TERRIAMAP_CONTAINER_PORT: 3001
  TERRIAMAP_DESIRED_COUNT: 1
  TERRIAMAP_DOMAIN: "terriamap.mapkraken.com"
  TERRIAMAP_ECR_URL: "${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/terriamap:latest"
