sit:
  TERRIAMAP_CONTAINER_PORT: 3001
  TERRIAMAP_DESIRED_COUNT: 1
  TERRIAMAP_DOMAIN: "${self:provider.stage}-terriamap.mapkraken.com"
  TERRIAMAP_ECR_URL: "${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:provider.stage}sit-terriamap:latest"
stg:
  TERRIAMAP_CONTAINER_PORT: 3001
  TERRIAMAP_DESIRED_COUNT: 1
  TERRIAMAP_DOMAIN: "${self:provider.stage}-terriamap.mapkraken.com"
  TERRIAMAP_ECR_URL: "${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:provider.stage}sit-terriamap:latest"
prd:
  TERRIAMAP_CONTAINER_PORT: 3001
  TERRIAMAP_DESIRED_COUNT: 1
  TERRIAMAP_DOMAIN: "${self:provider.stage}-terriamap.mapkraken.com"
  TERRIAMAP_ECR_URL: "${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:provider.stage}sit-terriamap:latest"
