Resources:
  TargetGroupTerriamap:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${self:provider.stage}-terriamap-targetgroup"
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue ${self:provider.stage}-VPC
      TargetType: ip
      HealthCheckPort: ${self:custom.environment.TERRIAMAP_CONTAINER_PORT}
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-302
      Tags:
        - Key: Name
          Value: !Sub "${self:provider.stage}-terriamap"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
        - Key: stickiness.enabled
          Value: true
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: 86400
        - Key: load_balancing.algorithm.type
          Value: round_robin