Resources: 
  ListenerRuleTerriamap:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: 
      - TargetGroupTerriamap
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupTerriamap
      Conditions:
        - Field: host-header
          Values:
            - ${self:custom.environment.TERRIAMAP_DOMAIN}
      ListenerArn: !ImportValue ${self:provider.stage}-ListenerHTTPSTerriamapArn
      Priority: 12