service: fargate

provider: 
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'sit'}
  deploymentBucket: 
    name: ${self:provider.stage}-mapkraken-serverless-stacks
    maxPreviousDeploymentArtifacts: 2
    tags:
      Environment: ${self:provider.stage}  # Changed to object format
      Project: mapkraken
      Stack: ${self:service}

custom:
  environment: ${file(./environment.yml):${self:provider.stage}}
  namespace: mapkraken-fargate
  namespaceShort: labs
resources:
  - ${file(./resources-fargate.yml)}
  # - ${file(./resources-listeners.yml)}
  - ${file(./resources-s3.yml)}
  # - ${file(./resources-targetgroup.yml)}