Resources:
  MapKrakenLabsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mapkraken-labs-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false  # This allows public policies to be applied
        RestrictPublicBuckets: false
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - MapKrakenLabsBucket
    Properties:
      Bucket: !Ref MapKrakenLabsBucket
      PolicyDocument:
        Version: "2012-10-17"  # Added required Version
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: 
              - "s3:GetObject"
            Resource: !Join ['', ['arn:aws:s3:::', !Ref MapKrakenLabsBucket, '/*']]
Outputs:
  MapKrakenLabsBucketWebsiteURL:
    Description: "Website URL of the MapKrakenLabsBucket"
    Value: !Sub "${MapKrakenLabsBucket}.s3-website-${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-MapKrakenLabsBucketNameWebsiteURL"
  MapKrakenLabsBucketName:
    Description: "Name of the MapKrakenLabsBucket"
    Value: !Ref MapKrakenLabsBucket
    Export:
      Name: !Sub "${AWS::StackName}-MapKrakenLabsBucketName"

