Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.environment.BUCKET_NAME}
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - SiteBucket
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: 
              - "s3:GetObject"
            Resource: !Join ['', ['arn:aws:s3:::', !Ref SiteBucket, '/*']]
Outputs:
  SiteBucketWebsiteURL:
    Description: "Website URL of the ${self:custom.environment.APP_NAME} site bucket"
    Value: !Sub "${SiteBucket}.s3-website-${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${self:provider.stage}-BucketNameWebsiteURL"
  BucketName:
    Description: "Name of the ${self:custom.environment.APP_NAME} site bucket"
    Value: !Ref SiteBucket
    Export:
      Name: !Sub "${self:provider.stage}-BucketName"
  DomainName:
    Description: The domain name of the ${self:custom.environment.APP_NAME} S3 bucket
    Value: !GetAtt SiteBucket.DomainName
    Export:
      Name: !Sub "${self:provider.stage}-DomainName"


