service: s3

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: sit

plugins:
  - serverless-s3-sync
  
custom:
  environment: ${file(./environment.yml):${self:provider.stage}}
  namespace: mapkraken
  namespaceShort: labs

  s3Sync:
    - bucketName: mapkraken-labs-bucket
      localDir: ./sync/mapkraken-labs

resources:
  - ${file(./resources-mapkraken-labs.yml)}
