service: s3

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'sit'}
  deploymentBucket: 
    name: ${self:provider.stage}-mapkraken-serverless-stacks
    maxPreviousDeploymentArtifacts: 2
    tags:
      Environment: ${self:provider.stage}  # Changed to object format
      Project: mapkraken
      Stack: ${self:service}

plugins:
  - serverless-s3-sync
  
custom:
  environment: ${file(./environment.yml):${self:provider.stage}}
  namespace: mapkraken
  namespaceShort: labs
  
  s3Sync:
    - bucketName: ${self:provider.stage}-${self:custom.environment.BUCKET_NAME}
      localDir: ./sync/mapkraken
    - bucketName: ${self:provider.stage}-labs-${self:custom.environment.BUCKET_NAME}
      localDir: ./sync/mapkraken-labs
    - bucketName: ${self:provider.stage}-territory-mapper-${self:custom.environment.BUCKET_NAME}
      localDir: ./sync/territory-mapper

resources:
  - ${file(./conditions.yml)}
  - ${file(./resources-mapkraken-labs.yml)}
