AWSTemplateFormatVersion: "2010-09-09"
Description: SecretsManager for applications

Resources:
  # Secrets Manager Secret for PostGIS Credentials
  PostGISSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${self:provider.stage}/rds/postgis-secret"
      Description: "Secret for PostGIS database credentials"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "koopuser"}'  # Default username, can be parameterized
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludePunctuation: true
      Tags:
        - Key: Name
          Value: !Sub "${self:provider.stage}-postgis-secret"
  GithubPATSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${self:provider.stage}/rds/github-pat-secret"
      Description: "PAT value for github"
     
      Tags:
        - Key: Name
          Value: !Sub "${self:provider.stage}-github-pat"

Outputs: 
  PostGISSecretArn:
    Description: ARN of the Secrets Manager secret for database credentials
    Value: !Ref PostGISSecret
    Export:
      Name: !Sub "${self:provider.stage}-PostGISSecretArn"