Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Condition: OnlyCreateResourceInPRD
    Properties:
      Name: ${self:custom.environment.DOMAIN_NAME}
      HostedZoneConfig:
        Comment: ${self:custom.environment.ZONE_COMMENT}
      HostedZoneTags: ${self:custom.environment.HOSTED_ZONE_TAGS}

Outputs:
  HostedZoneId:
    Condition: OnlyCreateResourceInPRD
    Value: !Ref HostedZone
    Export:
      Name: !Sub "HostedZoneId"