Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: ${self:custom.environment.DOMAIN_NAME}
      HostedZoneConfig:
        Comment: ${self:custom.environment.ZONE_COMMENT}
      HostedZoneTags: ${self:custom.environment.HOSTED_ZONE_TAGS}
Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Export:
      Name: !Sub "${self:provider.stage}-HostedZoneId"
  NameServers:
    Value: !Join [',', !GetAtt HostedZone.NameServers]
    Export:
      Name: !Sub "${self:provider.stage}-NameServers"