AWSTemplateFormatVersion: '2010-09-09'
Description: Bastion host for accessing private EC2
Resources:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Bastion SG with SSH access
      VpcId: !ImportValue ${self:provider.stage}-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Restrict to your IP in production
      Tags:
        - Key: Name
          Value: ${self:provider.stage}-bastion-sg

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08b5b3a93ed654d19 # Update if needed
      SubnetId: !ImportValue ${self:provider.stage}-PublicSubnet1
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      KeyName: !Ref Ec2KeyPair  # Reuse sit-KeyPair
      Tags:
        - Key: Name
          Value: ${self:provider.stage}-bastion

Outputs:
  BastionPublicIP:
    Value: !GetAtt BastionInstance.PublicIp
    Export:
      Name: ${self:provider.stage}-BastionPublicIP